version: '3.8'
services:
  user-service:
    build: ./user-service
    environment:
      DATABASE_URL: postgres://user:password@db/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  product-service:
    build: ./product-service
    environment:
      DATABASE_URL: mongodb://db/mongodb 
    ports:
      - "3000:3000"

  order-service:
    build: ./order-service 
    ports:
      - "8080:8080"

  db:
    image: postgres:latest 
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: postgres 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: